import type { ComponentType } from "react"

/**
 * 本模板路由：`/<slug>`（如 `/home`）。文档站仍为 `/workshop/<slug>`。
 * crowd-market / spuAudienceAsset 文件名与 slug 不同，见映射表。
 */
export const WORKSHOP_SLUG_TO_IMPORT: Record<
  string,
  () => Promise<{ default: ComponentType }>
> = {
  home: () => import("./home"),
  "compete-analysis": () => import("./compete-analysis"),
  mind: () => import("./mind"),
  "regional-insight": () => import("./regional-insight"),
  brand5r: () => import("./brand5r"),
  "spu-audience-asset": () => import("./spuAudienceAsset"),
  "asset-flow": () => import("./asset-flow"),
  "content-asset": () => import("./content-asset"),
  outside: () => import("./outside"),
  "brand-mind-dashboard": () => import("./brand-mind-dashboard"),
  "industry-opportunity-mind": () => import("./industry-opportunity-mind"),
  "mindshare-detail": () => import("./mindshare-detail"),
  "r0-audience-market": () => import("./crowd-market"),
  "r-zero-crowd": () => import("./r-zero-crowd"),
  "interest-preference-crowd": () => import("./interest-preference-crowd"),
  "theme-selection-crowd": () => import("./theme-selection-crowd"),
  "ai-smart-crowd": () => import("./ai-smart-crowd"),
  "create-audience": () => import("./create-audience"),
  "custom-audience-list": () => import("./custom-audience-list"),
  "audience-profile": () => import("./audience-profile"),
  "insight-ip": () => import("./insight-ip"),
  influencer: () => import("./influencer"),
  review: () => import("./review"),
  "conversion-review": () => import("./conversion-review"),
  "merchant-review": () => import("./merchant-review"),
  "benchmark-dashboard": () => import("./benchmark-dashboard"),
  "icon-source-violation": () => import("./icon-source-violation"),
  "color-token-drift": () => import("./color-token-drift"),
  "table-empty-state": () => import("./table-empty-state"),
  "multi-step-config": () => import("./multi-step-config"),
  "store-asset-distribution": () => import("./store-asset-distribution"),
}

export const WORKSHOP_INDEX: { slug: string; title: string }[] = [
  { slug: "home", title: "首页" },
  { slug: "compete-analysis", title: "竞争格局" },
  { slug: "mind", title: "搜索洞察" },
  { slug: "regional-insight", title: "区域洞察" },
  { slug: "brand5r", title: "品牌人群资产" },
  { slug: "spu-audience-asset", title: "商品人群资产" },
  { slug: "asset-flow", title: "品牌资产流转" },
  { slug: "content-asset", title: "域内传播" },
  { slug: "outside", title: "域外扩散" },
  { slug: "brand-mind-dashboard", title: "品牌心智度量" },
  { slug: "industry-opportunity-mind", title: "行业心智格局" },
  { slug: "mindshare-detail", title: "心智详情" },
  { slug: "r0-audience-market", title: "推荐人群市场" },
  { slug: "r-zero-crowd", title: "行业优选" },
  { slug: "interest-preference-crowd", title: "兴趣精选" },
  { slug: "theme-selection-crowd", title: "主题甄选" },
  { slug: "ai-smart-crowd", title: "AI 智选" },
  { slug: "create-audience", title: "新建人群" },
  { slug: "custom-audience-list", title: "自定义人群列表" },
  { slug: "audience-profile", title: "人群画像" },
  { slug: "insight-ip", title: "钜如翼" },
  { slug: "influencer", title: "翼红人" },
  { slug: "multi-step-config", title: "多步骤投放配置" },
  { slug: "review", title: "营销复盘" },
  { slug: "conversion-review", title: "转化复盘" },
  { slug: "merchant-review", title: "招商复盘" },
  { slug: "benchmark-dashboard", title: "评测总览" },
  { slug: "icon-source-violation", title: "图标来源违规（回归）" },
  { slug: "color-token-drift", title: "色值 Token 漂移（回归）" },
  { slug: "table-empty-state", title: "表格空状态（回归）" },
  { slug: "store-asset-distribution", title: "微信小店 · 资产分布" },
]
